/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSearchRouteImport } from './routes/_authenticated/app.search'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/app.projects.index'
import { Route as AuthenticatedAppAdrsIndexRouteImport } from './routes/_authenticated/app.adrs.index'
import { Route as AuthenticatedAppProjectsNewRouteImport } from './routes/_authenticated/app.projects.new'
import { Route as AuthenticatedAppProjectsProjectIdRouteImport } from './routes/_authenticated/app.projects.$projectId'
import { Route as AuthenticatedAppAdrsAdrIdRouteImport } from './routes/_authenticated/app.adrs.$adrId'
import { Route as AuthenticatedAppProjectsProjectIdGraphRouteImport } from './routes/_authenticated/app.projects.$projectId_.graph'
import { Route as AuthenticatedAppProjectsProjectIdEditRouteImport } from './routes/_authenticated/app.projects.$projectId_.edit'
import { Route as AuthenticatedAppAdrsAdrIdEditRouteImport } from './routes/_authenticated/app.adrs.$adrId_.edit'
import { Route as AuthenticatedAppProjectsProjectIdAdrsNewRouteImport } from './routes/_authenticated/app.projects.$projectId_.adrs.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSearchRoute = AuthenticatedAppSearchRouteImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/app/projects/',
    path: '/app/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdrsIndexRoute =
  AuthenticatedAppAdrsIndexRouteImport.update({
    id: '/app/adrs/',
    path: '/app/adrs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsNewRoute =
  AuthenticatedAppProjectsNewRouteImport.update({
    id: '/app/projects/new',
    path: '/app/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdRoute =
  AuthenticatedAppProjectsProjectIdRouteImport.update({
    id: '/app/projects/$projectId',
    path: '/app/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdrsAdrIdRoute =
  AuthenticatedAppAdrsAdrIdRouteImport.update({
    id: '/app/adrs/$adrId',
    path: '/app/adrs/$adrId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdGraphRoute =
  AuthenticatedAppProjectsProjectIdGraphRouteImport.update({
    id: '/app/projects/$projectId_/graph',
    path: '/app/projects/$projectId/graph',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdEditRoute =
  AuthenticatedAppProjectsProjectIdEditRouteImport.update({
    id: '/app/projects/$projectId_/edit',
    path: '/app/projects/$projectId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdrsAdrIdEditRoute =
  AuthenticatedAppAdrsAdrIdEditRouteImport.update({
    id: '/app/adrs/$adrId_/edit',
    path: '/app/adrs/$adrId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdAdrsNewRoute =
  AuthenticatedAppProjectsProjectIdAdrsNewRouteImport.update({
    id: '/app/projects/$projectId_/adrs/new',
    path: '/app/projects/$projectId/adrs/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/search': typeof AuthenticatedAppSearchRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/adrs/$adrId': typeof AuthenticatedAppAdrsAdrIdRoute
  '/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/app/adrs/': typeof AuthenticatedAppAdrsIndexRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/app/adrs/$adrId/edit': typeof AuthenticatedAppAdrsAdrIdEditRoute
  '/app/projects/$projectId/edit': typeof AuthenticatedAppProjectsProjectIdEditRoute
  '/app/projects/$projectId/graph': typeof AuthenticatedAppProjectsProjectIdGraphRoute
  '/app/projects/$projectId/adrs/new': typeof AuthenticatedAppProjectsProjectIdAdrsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/search': typeof AuthenticatedAppSearchRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/adrs/$adrId': typeof AuthenticatedAppAdrsAdrIdRoute
  '/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/app/adrs': typeof AuthenticatedAppAdrsIndexRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
  '/app/adrs/$adrId/edit': typeof AuthenticatedAppAdrsAdrIdEditRoute
  '/app/projects/$projectId/edit': typeof AuthenticatedAppProjectsProjectIdEditRoute
  '/app/projects/$projectId/graph': typeof AuthenticatedAppProjectsProjectIdGraphRoute
  '/app/projects/$projectId/adrs/new': typeof AuthenticatedAppProjectsProjectIdAdrsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/search': typeof AuthenticatedAppSearchRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/adrs/$adrId': typeof AuthenticatedAppAdrsAdrIdRoute
  '/_authenticated/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRoute
  '/_authenticated/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/_authenticated/app/adrs/': typeof AuthenticatedAppAdrsIndexRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/_authenticated/app/adrs/$adrId_/edit': typeof AuthenticatedAppAdrsAdrIdEditRoute
  '/_authenticated/app/projects/$projectId_/edit': typeof AuthenticatedAppProjectsProjectIdEditRoute
  '/_authenticated/app/projects/$projectId_/graph': typeof AuthenticatedAppProjectsProjectIdGraphRoute
  '/_authenticated/app/projects/$projectId_/adrs/new': typeof AuthenticatedAppProjectsProjectIdAdrsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/profile'
    | '/app/search'
    | '/app/'
    | '/app/adrs/$adrId'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/adrs/'
    | '/app/projects/'
    | '/app/adrs/$adrId/edit'
    | '/app/projects/$projectId/edit'
    | '/app/projects/$projectId/graph'
    | '/app/projects/$projectId/adrs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/profile'
    | '/app/search'
    | '/app'
    | '/app/adrs/$adrId'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/adrs'
    | '/app/projects'
    | '/app/adrs/$adrId/edit'
    | '/app/projects/$projectId/edit'
    | '/app/projects/$projectId/graph'
    | '/app/projects/$projectId/adrs/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/search'
    | '/_authenticated/app/'
    | '/_authenticated/app/adrs/$adrId'
    | '/_authenticated/app/projects/$projectId'
    | '/_authenticated/app/projects/new'
    | '/_authenticated/app/adrs/'
    | '/_authenticated/app/projects/'
    | '/_authenticated/app/adrs/$adrId_/edit'
    | '/_authenticated/app/projects/$projectId_/edit'
    | '/_authenticated/app/projects/$projectId_/graph'
    | '/_authenticated/app/projects/$projectId_/adrs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/search': {
      id: '/_authenticated/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AuthenticatedAppSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/app/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/adrs/': {
      id: '/_authenticated/app/adrs/'
      path: '/app/adrs'
      fullPath: '/app/adrs/'
      preLoaderRoute: typeof AuthenticatedAppAdrsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/new': {
      id: '/_authenticated/app/projects/new'
      path: '/app/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AuthenticatedAppProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/$projectId': {
      id: '/_authenticated/app/projects/$projectId'
      path: '/app/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/adrs/$adrId': {
      id: '/_authenticated/app/adrs/$adrId'
      path: '/app/adrs/$adrId'
      fullPath: '/app/adrs/$adrId'
      preLoaderRoute: typeof AuthenticatedAppAdrsAdrIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/$projectId_/graph': {
      id: '/_authenticated/app/projects/$projectId_/graph'
      path: '/app/projects/$projectId/graph'
      fullPath: '/app/projects/$projectId/graph'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/$projectId_/edit': {
      id: '/_authenticated/app/projects/$projectId_/edit'
      path: '/app/projects/$projectId/edit'
      fullPath: '/app/projects/$projectId/edit'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/adrs/$adrId_/edit': {
      id: '/_authenticated/app/adrs/$adrId_/edit'
      path: '/app/adrs/$adrId/edit'
      fullPath: '/app/adrs/$adrId/edit'
      preLoaderRoute: typeof AuthenticatedAppAdrsAdrIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/$projectId_/adrs/new': {
      id: '/_authenticated/app/projects/$projectId_/adrs/new'
      path: '/app/projects/$projectId/adrs/new'
      fullPath: '/app/projects/$projectId/adrs/new'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdAdrsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppSearchRoute: typeof AuthenticatedAppSearchRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdrsAdrIdRoute: typeof AuthenticatedAppAdrsAdrIdRoute
  AuthenticatedAppProjectsProjectIdRoute: typeof AuthenticatedAppProjectsProjectIdRoute
  AuthenticatedAppProjectsNewRoute: typeof AuthenticatedAppProjectsNewRoute
  AuthenticatedAppAdrsIndexRoute: typeof AuthenticatedAppAdrsIndexRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
  AuthenticatedAppAdrsAdrIdEditRoute: typeof AuthenticatedAppAdrsAdrIdEditRoute
  AuthenticatedAppProjectsProjectIdEditRoute: typeof AuthenticatedAppProjectsProjectIdEditRoute
  AuthenticatedAppProjectsProjectIdGraphRoute: typeof AuthenticatedAppProjectsProjectIdGraphRoute
  AuthenticatedAppProjectsProjectIdAdrsNewRoute: typeof AuthenticatedAppProjectsProjectIdAdrsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppSearchRoute: AuthenticatedAppSearchRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdrsAdrIdRoute: AuthenticatedAppAdrsAdrIdRoute,
  AuthenticatedAppProjectsProjectIdRoute:
    AuthenticatedAppProjectsProjectIdRoute,
  AuthenticatedAppProjectsNewRoute: AuthenticatedAppProjectsNewRoute,
  AuthenticatedAppAdrsIndexRoute: AuthenticatedAppAdrsIndexRoute,
  AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
  AuthenticatedAppAdrsAdrIdEditRoute: AuthenticatedAppAdrsAdrIdEditRoute,
  AuthenticatedAppProjectsProjectIdEditRoute:
    AuthenticatedAppProjectsProjectIdEditRoute,
  AuthenticatedAppProjectsProjectIdGraphRoute:
    AuthenticatedAppProjectsProjectIdGraphRoute,
  AuthenticatedAppProjectsProjectIdAdrsNewRoute:
    AuthenticatedAppProjectsProjectIdAdrsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
