/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedAdrsIndexRouteImport } from './routes/_authenticated/adrs.index'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedAdrsAdrIdRouteImport } from './routes/_authenticated/adrs.$adrId'
import { Route as AuthenticatedProjectsProjectIdGraphRouteImport } from './routes/_authenticated/projects.$projectId_.graph'
import { Route as AuthenticatedProjectsProjectIdEditRouteImport } from './routes/_authenticated/projects.$projectId_.edit'
import { Route as AuthenticatedAdrsAdrIdEditRouteImport } from './routes/_authenticated/adrs.$adrId_.edit'
import { Route as AuthenticatedProjectsProjectIdAdrsNewRouteImport } from './routes/_authenticated/projects.$projectId_.adrs.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdrsIndexRoute = AuthenticatedAdrsIndexRouteImport.update({
  id: '/adrs/',
  path: '/adrs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdrsAdrIdRoute = AuthenticatedAdrsAdrIdRouteImport.update({
  id: '/adrs/$adrId',
  path: '/adrs/$adrId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsProjectIdGraphRoute =
  AuthenticatedProjectsProjectIdGraphRouteImport.update({
    id: '/projects/$projectId_/graph',
    path: '/projects/$projectId/graph',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEditRoute =
  AuthenticatedProjectsProjectIdEditRouteImport.update({
    id: '/projects/$projectId_/edit',
    path: '/projects/$projectId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdrsAdrIdEditRoute =
  AuthenticatedAdrsAdrIdEditRouteImport.update({
    id: '/adrs/$adrId_/edit',
    path: '/adrs/$adrId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdAdrsNewRoute =
  AuthenticatedProjectsProjectIdAdrsNewRouteImport.update({
    id: '/projects/$projectId_/adrs/new',
    path: '/projects/$projectId/adrs/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/adrs/$adrId': typeof AuthenticatedAdrsAdrIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/adrs/': typeof AuthenticatedAdrsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/adrs/$adrId/edit': typeof AuthenticatedAdrsAdrIdEditRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
  '/projects/$projectId/graph': typeof AuthenticatedProjectsProjectIdGraphRoute
  '/projects/$projectId/adrs/new': typeof AuthenticatedProjectsProjectIdAdrsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/adrs/$adrId': typeof AuthenticatedAdrsAdrIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/adrs': typeof AuthenticatedAdrsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/adrs/$adrId/edit': typeof AuthenticatedAdrsAdrIdEditRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
  '/projects/$projectId/graph': typeof AuthenticatedProjectsProjectIdGraphRoute
  '/projects/$projectId/adrs/new': typeof AuthenticatedProjectsProjectIdAdrsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/adrs/$adrId': typeof AuthenticatedAdrsAdrIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/adrs/': typeof AuthenticatedAdrsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/adrs/$adrId_/edit': typeof AuthenticatedAdrsAdrIdEditRoute
  '/_authenticated/projects/$projectId_/edit': typeof AuthenticatedProjectsProjectIdEditRoute
  '/_authenticated/projects/$projectId_/graph': typeof AuthenticatedProjectsProjectIdGraphRoute
  '/_authenticated/projects/$projectId_/adrs/new': typeof AuthenticatedProjectsProjectIdAdrsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/search'
    | '/adrs/$adrId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/adrs/'
    | '/projects/'
    | '/adrs/$adrId/edit'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/graph'
    | '/projects/$projectId/adrs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/search'
    | '/adrs/$adrId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/adrs'
    | '/projects'
    | '/adrs/$adrId/edit'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/graph'
    | '/projects/$projectId/adrs/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/adrs/$adrId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/adrs/'
    | '/_authenticated/projects/'
    | '/_authenticated/adrs/$adrId_/edit'
    | '/_authenticated/projects/$projectId_/edit'
    | '/_authenticated/projects/$projectId_/graph'
    | '/_authenticated/projects/$projectId_/adrs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adrs/': {
      id: '/_authenticated/adrs/'
      path: '/adrs'
      fullPath: '/adrs/'
      preLoaderRoute: typeof AuthenticatedAdrsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adrs/$adrId': {
      id: '/_authenticated/adrs/$adrId'
      path: '/adrs/$adrId'
      fullPath: '/adrs/$adrId'
      preLoaderRoute: typeof AuthenticatedAdrsAdrIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId_/graph': {
      id: '/_authenticated/projects/$projectId_/graph'
      path: '/projects/$projectId/graph'
      fullPath: '/projects/$projectId/graph'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId_/edit': {
      id: '/_authenticated/projects/$projectId_/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adrs/$adrId_/edit': {
      id: '/_authenticated/adrs/$adrId_/edit'
      path: '/adrs/$adrId/edit'
      fullPath: '/adrs/$adrId/edit'
      preLoaderRoute: typeof AuthenticatedAdrsAdrIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId_/adrs/new': {
      id: '/_authenticated/projects/$projectId_/adrs/new'
      path: '/projects/$projectId/adrs/new'
      fullPath: '/projects/$projectId/adrs/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAdrsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedAdrsAdrIdRoute: typeof AuthenticatedAdrsAdrIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedAdrsIndexRoute: typeof AuthenticatedAdrsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedAdrsAdrIdEditRoute: typeof AuthenticatedAdrsAdrIdEditRoute
  AuthenticatedProjectsProjectIdEditRoute: typeof AuthenticatedProjectsProjectIdEditRoute
  AuthenticatedProjectsProjectIdGraphRoute: typeof AuthenticatedProjectsProjectIdGraphRoute
  AuthenticatedProjectsProjectIdAdrsNewRoute: typeof AuthenticatedProjectsProjectIdAdrsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedAdrsAdrIdRoute: AuthenticatedAdrsAdrIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedAdrsIndexRoute: AuthenticatedAdrsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedAdrsAdrIdEditRoute: AuthenticatedAdrsAdrIdEditRoute,
  AuthenticatedProjectsProjectIdEditRoute:
    AuthenticatedProjectsProjectIdEditRoute,
  AuthenticatedProjectsProjectIdGraphRoute:
    AuthenticatedProjectsProjectIdGraphRoute,
  AuthenticatedProjectsProjectIdAdrsNewRoute:
    AuthenticatedProjectsProjectIdAdrsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
