CREATE TABLE public.adr_collaboration_rooms (
  adr_id UUID PRIMARY KEY REFERENCES public.adrs(id) ON DELETE CASCADE,
  snapshot TEXT NOT NULL,
  created_by UUID NOT NULL REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.adr_collaboration_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  adr_id UUID NOT NULL REFERENCES public.adrs(id) ON DELETE CASCADE,
  update_data TEXT NOT NULL,
  created_by UUID NOT NULL REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX adr_collaboration_updates_adr_id_id_idx
  ON public.adr_collaboration_updates (adr_id, id);

GRANT SELECT, INSERT ON public.adr_collaboration_rooms TO authenticated;
GRANT SELECT, INSERT ON public.adr_collaboration_updates TO authenticated;
GRANT ALL ON public.adr_collaboration_rooms TO service_role;
GRANT ALL ON public.adr_collaboration_updates TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.adr_collaboration_updates_id_seq TO authenticated;

ALTER TABLE public.adr_collaboration_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.adr_collaboration_updates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Project members view ADR collaboration rooms"
  ON public.adr_collaboration_rooms FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1
    FROM public.adrs a
    WHERE a.id = adr_id
      AND (a.status <> 'draft' OR a.author_id = auth.uid())
      AND (public.has_role(auth.uid(), 'admin') OR public.is_project_member(auth.uid(), a.project_id))
  ));

CREATE POLICY "Project members create ADR collaboration rooms"
  ON public.adr_collaboration_rooms FOR INSERT TO authenticated
  WITH CHECK (
    created_by = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.adrs a
      WHERE a.id = adr_id
        AND (a.status <> 'draft' OR a.author_id = auth.uid())
        AND (public.has_role(auth.uid(), 'admin') OR public.is_project_member(auth.uid(), a.project_id))
    )
  );

CREATE POLICY "Project members view ADR collaboration updates"
  ON public.adr_collaboration_updates FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1
    FROM public.adrs a
    WHERE a.id = adr_id
      AND (a.status <> 'draft' OR a.author_id = auth.uid())
      AND (public.has_role(auth.uid(), 'admin') OR public.is_project_member(auth.uid(), a.project_id))
  ));

CREATE POLICY "Project members create ADR collaboration updates"
  ON public.adr_collaboration_updates FOR INSERT TO authenticated
  WITH CHECK (
    created_by = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.adrs a
      WHERE a.id = adr_id
        AND (a.status <> 'draft' OR a.author_id = auth.uid())
        AND (public.has_role(auth.uid(), 'admin') OR public.is_project_member(auth.uid(), a.project_id))
    )
  );
